'DATA_DIR': '../../Data'
'_DIR' : 'data_2'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'MODEL_NAME' : 'my_model_v_1_1'
'saved_model_file' : 'frozen_model_4_v18_5_1557413490.pb'
#'frozen_model_4_v18_5_1557413490.pb'
#'frozen_model_4_v18_8_1556726175.pb'
#  'frozen_model_4_v18_10_1557350563.pb'
#  'frozen_model_4_v18_5_1557349296.pb'
#  'frozen_model_3_v18_8_1556726175.pb'
#  'frozen_model_3_v18_5_1556920428.pb'