'DATA_DIR': '../../Data'
'_DIR' : 'data_1'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'MODEL_NAME' : 'my_model_v_1_2'
'eval_type' : 1
'VALIDATION_MODE' : True
'num_jobs' : 4
'data_1':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : False
  'num_epochs' : 200
  'op_dims' : 8,12,10
  'batchsize': 256
  'alpha' : 0.00025
  'lof_K' : 50
  'w_mean' : True
  'log_file' : 'results_data_1_log.csv'
'data_2':
  'learning_rate' : 0.0005
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : False
  'num_epochs' : 250
  'op_dims' : 8,6
  'batchsize': 512
  'alpha' : 0.01
  'lof_K' : 18
  'w_mean' : True
  'log_file' : 'results_data_2_log.csv'

'data_5':
  'learning_rate' : 0.0025
  'use_pretrained' : False
  'show_loss_figure' : False
  'save_loss_figure' : False
  'use_bias' : True
  'saved_model_file' : False
  'num_epochs' : 100
  'op_dims' : 8,2
  'batchsize': 128
  'alpha' : 0.1
  'lof_K' : 5
  'w_mean' : False
  'log_file' : 'results_data_5_log.csv'


# Best case :
# connect 4 : lof k =18 , alpha 0.0025 emb : 6
# covertype : lof k =20 , alpha 0.0025 emb : 10
