'DATA_DIR': '../../Data'
'_DIR' : 'data_2'
'OP_DIR' : 'output'
'SAVE_DIR' : 'save_dir'
'REFRESH_DATA' : True
'MODEL_NAME': 'model_ape'
'saved_model_file' : False
'data_1':
    'embed_size': 6
    'num_epocs': 3
    'batch_size': 256
'data_2':
    'embed_size': 8
    'num_epocs': 5
    'batch_size': 256
'data_5':
    'embed_size': 4
    'num_epocs' : 20
    'batch_size': 64
'dirs':
    - 'data_1'
    - 'data_2'
    - 'data_5'
